[package]
name = "polybar-custom-modules"
version = "0.0.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.55"
clap = { version = "3.1.1", features = ["derive"] }
battery = "0.7.8"
