[package]
name = "polybar-custom-modules"
version = "0.0.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.3", features = ["derive"] }
starship-battery = "0.8.1"
